# GitBook Configuration
# This file configures GitBook integration and build settings

# Root directory for documentation
root: ./docs

# Structure
structure:
  author: "CPH:SEC"
  readme: AI LLM Red Team Handbook.md
  summary: SUMMARY.md
  glossary: GLOSSARY.md
  languages: LANGS.md

# Redirects
redirects:
  README: docs/AI LLM Red Team Handbook.md

# PDF Options
pdf:
  pageNumbers: true
  fontSize: 12
  paperSize: a4
  margin:
    top: 56
    bottom: 56
    right: 62
    left: 62

# eBook Options
epub:
  stylesheet: styles/epub.css

mobi:
  stylesheet: styles/mobi.css

# Plugins
plugins:
  - search-plus
  - advanced-emoji
  - github
  - anchors
  - splitter
  - sharing
  - fontsettings
  - highlight
  - livereload
  - copy-code-button
  - code
  - mermaid-gb3
  - expandable-chapters-small
  - back-to-top-button
  - page-treeview
  - klipse
  - prism
  - insert-logo
  - 3-ba
  - theme-comscore

# Plugin Configuration
pluginsConfig:
  search-plus:
    maxIndexSize: 5000000

  github:
    url: https://github.com/shiva108/ai-llm-red-team-handbook

  sharing:
    facebook: false
    twitter: true
    linkedin: true
    all: ["facebook", "twitter", "linkedin", "weibo", "instapaper"]

  fontsettings:
    theme: "night"
    family: "sans"
    size: 2

  insert-logo:
    url: assets/banner.svg
    style: "background: none; max-height: 50px;"

  theme-comscore:
    token: "Your-Token-Here"
    position: "bottom"

# Variables
variables:
  handbook_version: "2.0"
  last_updated: "December 2024"
  author: "CPH:SEC"
  chapters_count: "24"

# Links
links:
  sidebar:
    GitHub Repository: https://github.com/shiva108/ai-llm-red-team-handbook
    Report Issue: https://github.com/shiva108/ai-llm-red-team-handbook/issues

# Styles
styles:
  website: styles/website.css
  ebook: styles/ebook.css
  pdf: styles/pdf.css
  mobi: styles/mobi.css
  epub: styles/epub.css
